name: Performance Tests Althea

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TARGET_URL: "http://54.226.195.234/"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  performance-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repository
        uses: actions/checkout@v4

      - name: Verification accessibilite du site
        run: |
          curl -I $TARGET_URL

      - name: Installer Hey
        run: |
          wget -O hey https://hey-release.s3.us-east-2.amazonaws.com/hey_linux_amd64
          chmod +x hey
          sudo mv hey /usr/local/bin/hey
          hey -h

      - name: Test performance avec Hey
        run: |
          hey -n 100 -c 10 $TARGET_URL | tee hey-result.txt

      - name: Test performance avec K6 via Docker
        run: |
          docker run --rm -v "$PWD:/scripts" grafana/k6 run /scripts/k6-test.js | tee k6-result.txt

      - name: Sauvegarder les resultats
        uses: actions/upload-artifact@v4
        with:
          name: performance-results
          path: |
            hey-result.txt
            k6-result.txt